.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 Arun Kumar Pariyar <zhangdongdong@uniontech.com>,
.\"
.TH "deepin-installer-bases "man" "2021-02-02" "deepin-installer manpage"
.\" Please adjust this date whenever revising the manpage.
.\" for manpage-specific macros, see man(7)

.SH NAME
deepin-installer-bases \- deepin installer
