#!/bin/bash
#
# Copyright (C) 2017 ~ 2018 Deepin Technology Co., Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Read kernel parameter and set global variables.

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

auto_install_mode=0

parse_cmdline() {
  for x in $(cat /proc/cmdline); do
    case $x in
      install-mode-cli=true)
        echo $x
        cli_mode=true
        ;;
	auto-deepin-installer)
        auto_install_mode=1
        ;;
      esac
  done
}

# Step1: generate default_screen.conf
# Step2: copy default_screen.conf to real system (in before_chroot 85_copy_settings_file.job)
# Step3: clean up. (in first_boot_setup.sh)
generate_default_screen_resolution() {
    local x11_conf_dir="/usr/share/X11/xorg.conf.d/"
    if [ ! -d $x11_conf_dir ]; then
        echo "$x11_conf_dir not exists"
        return 0;
    fi

    local default_screen_conf=$x11_conf_dir"default_screen.conf"
    if [ -f $default_screen_conf ]; then
        rm -rvf $default_screen_conf
    fi

    cat > "${default_screen_conf}" <<EOF
Section "Screen"
    Identifier "Screen0"
    SubSection "Display"
        Modes "1920x1080"
    EndSubSection
EndSection
EOF
}

parse_cmdline

if [ x"$cli_mode" = xtrue ]; then
    systemctl stop lightdm
    chvt 2
    systemctl restart deepin-installer-cli
else
    generate_default_screen_resolution
    if [ $auto_install_mode -eq 1 ]; then
       /usr/lib/live/config/1081-deepin-auto-install
    else
       /usr/lib/live/config/1082-deepin-livecd true
    fi
    systemctl restart lightdm
fi

