#!/bin/bash

 . /usr/share/deepin-installer/hooks/basic_utils.sh

start_checkmode() {
    echo "start checkmode..."
    init_checkmode
    #systemctl restart lightdm
}

start_backup() {
    echo "start backup..."
    init_backup
    # /sbin/shutdown -r now
}

start_firstboot() {
    echo "start first boot..."
    init_firstboot
    systemctl disable deepin-installer
    systemctl restart lightdm
}

start_system() {
    echo "start systemd..."
}

init_start() {
    local arg1=$1
    local system_backup_disable=$(installer_get "system_backup_disable")
    local system_check_mode=$(installer_get "system_check_mode")

    ## 判断是否进入审核模式
    if [ "x$system_check_mode" = "xtrue" ]; then
        start_checkmode
    fi

    ## 判断是否备份
    if [ ! -f /recovery/backup.flag ] && [ "x$system_backup_disable" != "xtrue" ]; then
        start_backup
    fi

    ## 判断是否进入后配置
    if [ "$arg1" = "0" ]; then
        start_firstboot
    elif [ "$arg1" = "2" ]; then
        start_system
    fi
}

init_setting() {
    echo "init setting"

     # 本地调试逻辑
    [ -f /usr/lib/live/mount/medium/oem/settings.ini ] && \
        cat /usr/lib/live/mount/medium/oem/settings.ini > /etc/deepin-installer.conf
    [ -f /usr/lib/live/mount/medium/oem/lightdm.conf ] && \
        cp /usr/lib/live/mount/medium/oem/lightdm.conf /etc/lightdm/lightdm.conf
}

main() {
    init_setting    #　提前初始化安装器配置，用于后续启动阶段的oem定制

    local mode=$(installer_get "system_installer_start_mode")
    echo "install mode: $mode"

    if [ ! -n "$mode" ]; then
        echo "installer start..."
        /usr/bin/deepin-installer-both  # 正常安装系统
    else
        echo "init start..."
        init_start $mode 　             # 启动烧录流程
    fi
}

main
